# Generated by Django 5.1.4 on 2026-06-18 10:24

import accounting.models
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=accounting.models.company_logo_directory_path, validators=[utils.validators.validate_image_size])),
                ('logo2', models.ImageField(blank=True, null=True, upload_to=accounting.models.company_logo2_directory_path, validators=[utils.validators.validate_image_size])),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to=accounting.models.stamps_directory_path, validators=[utils.validators.validate_image_size])),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=accounting.models.signature_directory_path, validators=[utils.validators.validate_image_size])),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('mfo', models.CharField(blank=True, max_length=10, null=True)),
                ('legal_reg_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chief_accountant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_official', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_official2', models.CharField(blank=True, max_length=30, null=True)),
                ('email_official', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_official2', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('website2', models.URLField(blank=True, null=True)),
                ('base_currency', models.CharField(default='TMT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Справочник',
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Тип цены',
                'verbose_name_plural': 'Типы цен',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код счета')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование счета')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа (нельзя делать проводки)')),
                ('account_type', models.CharField(choices=[('A', 'А'), ('P', 'П'), ('AP', 'АП')], default='AP', max_length=2, verbose_name='Вид счета')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subaccounts', to='accounting.account', verbose_name='Родительский счет')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'План счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название филиала')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код филиала')),
                ('is_head_office', models.BooleanField(default=False, verbose_name='Главный офис')),
                ('address', models.TextField(blank=True, verbose_name='Адрес филиала')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон филиала')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email филиала')),
                ('website', models.URLField(blank=True, verbose_name='Сайт филиала')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Управляющий')),
                ('manager_position', models.CharField(default='Директор филиала', max_length=255, verbose_name='Должность')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=accounting.models.branch_logo_directory_path)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=accounting.models.branch_signature_directory_path)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounting.companyprofile')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название контрагента')),
                ('type', models.CharField(choices=[('client', 'Клиент'), ('supplier', 'Поставщик'), ('both', 'Клиент и поставщик')], default='both', max_length=20)),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['extra_data'], name='counterparty_extra_data_gin')],
            },
        ),
        migrations.CreateModel(
            name='DirectoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounting.directory')),
            ],
            options={
                'verbose_name': 'Запись справочника',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер операции')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Дата проводки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведен')], db_index=True, default='draft', max_length=10, verbose_name='Статус операции')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Содержание / Комментарий')),
                ('source_document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID документа-источника')),
                ('source_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип документа-источника')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Журнал операций',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.productcategory')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул')),
                ('image_mode', models.CharField(choices=[('contain', 'Вписать'), ('cover', 'Заполнить')], default='contain', max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Штрихкод (EAN-13)')),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='QR-код / Серийный номер')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Себестоимость')),
                ('min_stock_level', models.IntegerField(default=0, verbose_name='Мин. остаток для заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounting.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounting.productcategory', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='accounting.tag', verbose_name='Теги')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounting.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SubcontoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название аналитики')),
                ('slug', models.SlugField(unique=True, verbose_name='Системный код (Slug)')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'accounting'), ('app_label', 'companies'), ('app_label', 'users'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Какую модель подключаем')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.directory', verbose_name='Динамический справочник')),
            ],
            options={
                'verbose_name': 'Вид субконто',
                'verbose_name_plural': 'Виды субконто',
            },
        ),
        migrations.CreateModel(
            name='AccountSubconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок вывода в интерфейсе (1, 2, 3)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_subcontos', to='accounting.account')),
                ('subconto_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.subcontotype', verbose_name='Вид субконто')),
            ],
            options={
                'verbose_name': 'Субконто счета',
                'verbose_name_plural': 'Субконто счетов',
                'ordering': ['order'],
                'unique_together': {('account', 'order')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='subcontos',
            field=models.ManyToManyField(related_name='accounts', through='accounting.AccountSubconto', to='accounting.subcontotype', verbose_name='Виды субконто'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной склад')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='accounting.branch')),
            ],
            options={
                'verbose_name': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='accounting.pricetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='accounting.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цены товаров',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='accounting.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
            },
        ),
        migrations.CreateModel(
            name='DirectoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да/Нет'), ('ref', 'Ссылка на другой справочник')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounting.directory')),
                ('ref_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.directory')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('directory', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=accounting.models.product_image_path, validators=[utils.validators.validate_image_size], verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Описание изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounting.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['product', 'is_main'], name='product_main_img_idx'), models.Index(fields=['product', 'sort_order'], name='product_sort_img_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='unique_main_product_image')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('subcontos_deb', models.JSONField(blank=True, default=dict, verbose_name='Субконто Дт (JSON)')),
                ('subcontos_krt', models.JSONField(blank=True, default=dict, verbose_name='Субконто Кт (JSON)')),
                ('account_deb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='accounting.account', verbose_name='Счет Дт')),
                ('account_krt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='accounting.account', verbose_name='Счет Кт')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.journalentry', verbose_name='Родительская операция')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['subcontos_deb'], name='tx_subcontos_deb_gin'), django.contrib.postgres.indexes.GinIndex(fields=['subcontos_krt'], name='tx_subcontos_krt_gin')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extra_data'], name='product_extra_data_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['qr_code'], name='product_qr_code_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'warehouse'], name='accounting__product_6c21aa_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['price_type'], name='accounting__price_t_b0f2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_9285a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product', 'warehouse', 'price_type'), name='unique_active_product_price', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['product'], name='accounting__product_b147b1_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['warehouse'], name='accounting__warehou_bb9d65_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_warehouse_product'),
        ),
    ]
