# Generated by Django 5.2.14 on 2026-05-21 06:22

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код счета')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование счета')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа (нельзя делать проводки)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subaccounts', to='accounting.account', verbose_name='Родительский счет')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'План счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер операции')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Дата проводки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведен')], db_index=True, default='draft', max_length=10, verbose_name='Статус операции')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Содержание / Комментарий')),
                ('source_document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID документа-источника')),
                ('source_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип документа-источника')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Журнал операций',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='SubcontoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название аналитики')),
                ('slug', models.SlugField(unique=True, verbose_name='Системный код (Slug)')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'accounting'), ('app_label', 'companies'), ('app_label', 'users'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Какую модель подключаем')),
            ],
            options={
                'verbose_name': 'Вид субконто',
                'verbose_name_plural': 'Виды субконто',
            },
        ),
        migrations.CreateModel(
            name='AccountSubconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок вывода в интерфейсе (1, 2, 3)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_subcontos', to='accounting.account')),
                ('subconto_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.subcontotype', verbose_name='Вид субконто')),
            ],
            options={
                'verbose_name': 'Субконто счета',
                'verbose_name_plural': 'Субконто счетов',
                'ordering': ['order'],
                'unique_together': {('account', 'order')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='subcontos',
            field=models.ManyToManyField(related_name='accounts', through='accounting.AccountSubconto', to='accounting.subcontotype', verbose_name='Виды субконто'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('subcontos_deb', models.JSONField(blank=True, default=dict, verbose_name='Субконто Дт (JSON)')),
                ('subcontos_krt', models.JSONField(blank=True, default=dict, verbose_name='Субконто Кт (JSON)')),
                ('account_deb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='accounting.account', verbose_name='Счет Дт')),
                ('account_krt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='accounting.account', verbose_name='Счет Кт')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.journalentry', verbose_name='Родительская операция')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['subcontos_deb'], name='tx_subcontos_deb_gin'), django.contrib.postgres.indexes.GinIndex(fields=['subcontos_krt'], name='tx_subcontos_krt_gin')],
            },
        ),
    ]
