# Generated by Django 5.1.4 on 2026-06-22 16:11

import accounting.models.company
import accounting.models.product
import datetime
import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
import utils.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название филиала')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код филиала')),
                ('is_head_office', models.BooleanField(default=False, verbose_name='Главный офис')),
                ('address', models.TextField(blank=True, verbose_name='Адрес филиала')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон филиала')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email филиала')),
                ('website', models.URLField(blank=True, verbose_name='Сайт филиала')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Управляющий')),
                ('manager_position', models.CharField(default='Директор филиала', max_length=255, verbose_name='Должность')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=accounting.models.company.branch_logo_directory_path)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=accounting.models.company.branch_signature_directory_path)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Закрытая дата')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Закрытый период',
                'verbose_name_plural': 'Закрытые периоды',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=accounting.models.company.company_logo_directory_path, validators=[utils.validators.validate_image_size])),
                ('logo2', models.ImageField(blank=True, null=True, upload_to=accounting.models.company.company_logo2_directory_path, validators=[utils.validators.validate_image_size])),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to=accounting.models.company.stamps_directory_path, validators=[utils.validators.validate_image_size])),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=accounting.models.company.signature_directory_path, validators=[utils.validators.validate_image_size])),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('mfo', models.CharField(blank=True, max_length=10, null=True)),
                ('legal_reg_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chief_accountant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_official', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_official2', models.CharField(blank=True, max_length=30, null=True)),
                ('email_official', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_official2', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('website2', models.URLField(blank=True, null=True)),
                ('base_currency', models.CharField(default='TMT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название контрагента')),
                ('type', models.CharField(choices=[('client', 'Клиент'), ('supplier', 'Поставщик'), ('both', 'Клиент и поставщик')], default='both', max_length=20)),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Справочник',
            },
        ),
        migrations.CreateModel(
            name='DirectoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да/Нет'), ('ref', 'Ссылка на другой справочник')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись справочника',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Табельный номер')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('dismiss_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], db_index=True, default='draft', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Журнал операций',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Тип цены',
                'verbose_name_plural': 'Типы цен',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул')),
                ('image_mode', models.CharField(choices=[('contain', 'Вписать'), ('cover', 'Заполнить')], default='contain', max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Штрихкод (EAN-13)')),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='QR-код / Серийный номер')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Себестоимость')),
                ('min_stock_level', models.IntegerField(default=0, verbose_name='Мин. остаток для заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Длина (см)')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Высота (см)')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Вес (кг)')),
                ('volume_m3', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Объем (м³)')),
                ('description', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=accounting.models.product.product_image_path, validators=[utils.validators.validate_image_size], verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Описание изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цены товаров',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('move', 'Перемещение')], db_index=True, max_length=4)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата операции')),
            ],
            options={
                'verbose_name': 'Движение по складу',
                'verbose_name_plural': 'Движения по складу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubcontoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название аналитики')),
                ('slug', models.SlugField(unique=True, verbose_name='Системный код (Slug)')),
            ],
            options={
                'verbose_name': 'Вид субконто',
                'verbose_name_plural': 'Виды субконто',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('side', models.CharField(choices=[('debit', 'Дебет'), ('credit', 'Кредит')], db_index=True, max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subcontos', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Строка операции',
                'verbose_name_plural': 'Строки операций',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной склад')),
            ],
            options={
                'verbose_name': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Остаток на складе',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код счета')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование счета')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа (нельзя делать проводки)')),
                ('account_type', models.CharField(choices=[('A', 'А'), ('P', 'П'), ('AP', 'АП')], default='AP', max_length=2, verbose_name='Вид счета')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subaccounts', to='accounting.account', verbose_name='Родительский счет')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'План счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountSubconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок вывода в интерфейсе (1, 2, 3)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_subcontos', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Субконто счета',
                'verbose_name_plural': 'Субконто счетов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('post', 'Проведение'), ('unpost', 'Отмена проведения')], db_index=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
            },
        ),
    ]
