# Generated by Django 5.1.4 on 2026-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Длина (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_m3',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Объем (м³)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ширина (см)'),
        ),
    ]
