# Generated by Django 5.1.4 on 2026-06-02 11:24

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_counterparty_product_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=accounting.models.company_logo_directory_path)),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to=accounting.models.stamps_directory_path)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=accounting.models.signature_directory_path)),
                ('tax_id', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=50)),
                ('mfo', models.CharField(max_length=10)),
                ('legal_reg_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('director_name', models.CharField(max_length=255)),
                ('chief_accountant_name', models.CharField(max_length=255)),
                ('phone_official', models.CharField(blank=True, max_length=30)),
                ('phone_official2', models.CharField(blank=True, max_length=30)),
                ('email_official', models.EmailField(blank=True, max_length=254)),
                ('email_official2', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('website2', models.URLField(blank=True)),
                ('base_currency', models.CharField(default='TMT', max_length=10)),
            ],
        ),
    ]
