# Generated by Django 5.1.4 on 2026-06-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название филиала')),
                ('address', models.TextField(blank=True, verbose_name='Адрес филиала')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон филиала')),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounting.companyprofile', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
    ]
