# Generated by Django 5.1.4 on 2026-06-23 08:46

import datetime
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_auditlog_audit_changed_data_gin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('in', 'Приходная накладная'), ('out', 'Расходная накладная'), ('move', 'Перемещение'), ('return_in', 'Возврат от покупателя'), ('return_out', 'Возврат поставщику')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], db_index=True, default='draft', max_length=10)),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='accounting.document')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.branch')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('default_price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounting.pricetype', verbose_name='Тип цены по умолчанию')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='accounting.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_documents', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.warehouse')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_in', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='№ строки')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.document')),
                ('price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.pricetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_items', to='accounting.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.unit')),
            ],
            options={
                'verbose_name': 'Строка документа',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Водитель'), ('seller', 'Продавец'), ('loader', 'Грузчик'), ('cashier', 'Кассир'), ('manager', 'Менеджер'), ('other', 'Другое')], default='other', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='accounting.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_participations', to='accounting.employee')),
            ],
            options={
                'verbose_name': 'Участник документа',
                'verbose_name_plural': 'Участники документа',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'status', 'date'], name='accounting__documen_b6cf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['counterparty', 'date'], name='accounting__counter_9b4314_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['warehouse', 'date'], name='accounting__warehou_fae432_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extra_data'], name='document_extra_data_gin'),
        ),
        migrations.AddConstraint(
            model_name='documentitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='document_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='documentparticipant',
            constraint=models.UniqueConstraint(fields=('document', 'employee', 'role'), name='unique_document_employee_role'),
        ),
    ]
