# Generated by Django 5.1.4 on 2026-06-06 07:00

import accounting.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to=accounting.models.company_logo2_directory_path, validators=[utils.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounting.models.company_logo_directory_path, validators=[utils.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounting.models.signature_directory_path, validators=[utils.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounting.models.stamps_directory_path, validators=[utils.validators.validate_image_size]),
        ),
    ]
