# Generated by Django 5.1.4 on 2026-06-19 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_closedperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата операции'),
        ),
    ]
