# Generated by Django 5.1.4 on 2026-06-24 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_userscope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='closedperiod',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_periods', to='accounting.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='closedperiod',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_periods', to='accounting.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='closedperiod',
            name='date',
            field=models.DateField(verbose_name='Закрытая дата'),
        ),
        migrations.AddConstraint(
            model_name='closedperiod',
            constraint=models.UniqueConstraint(fields=('date', 'branch', 'warehouse'), name='unique_closed_period'),
        ),
    ]
