# Generated by Django 5.1.4 on 2026-06-24 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_closedperiod_branch_closedperiod_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ratio', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Кол-во на единицу основного товара')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена по умолчанию (0 = бесплатно)')),
                ('bundle_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundled_in', to='accounting.product', verbose_name='Комплектующий товар')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='accounting.product', verbose_name='Основной товар')),
            ],
            options={
                'verbose_name': 'Комплектующий товар',
                'verbose_name_plural': 'Комплектующие товары',
                'indexes': [models.Index(fields=['product'], name='bundle_product_idx')],
                'unique_together': {('product', 'bundle_product')},
            },
        ),
    ]
