# Generated by Django 5.1.4 on 2026-06-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_companyprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код филиала'),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email филиала'),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_head_office',
            field=models.BooleanField(default=False, verbose_name='Главный офис'),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/branches/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Управляющий'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_position',
            field=models.CharField(default='Директор филиала', max_length=255, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='branch',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/branches/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт филиала'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounting.companyprofile'),
        ),
    ]
