# Generated by Django 5.1.4 on 2026-06-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_employee_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('max_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume_discounts', to='accounting.pricetype', verbose_name='Тип цены (null = для всех)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_discounts', to='accounting.product')),
            ],
            options={
                'verbose_name': 'Скидка по объёму',
                'ordering': ['min_qty'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='volume_discount_percent_range')],
            },
        ),
    ]
