# Generated by Django 5.1.4 on 2026-06-30 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_volumediscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='accounting.branch'),
            preserve_default=False,
        ),
    ]
