# Generated by Django 5.1.4 on 2026-06-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_directory_subcontotype_directory_directoryrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('A', 'Активный'), ('P', 'Пассивный'), ('AP', 'Активно-Пассивный')], default='AP', max_length=2, verbose_name='Вид счета'),
        ),
    ]
