# Generated by Django 5.1.4 on 2026-06-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_warehouse_branch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productprice',
            name='unique_active_product_price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='accounting.branch', verbose_name='Филиал (если warehouse не задан — цена на весь филиал)'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'branch'], name='accounting__product_93ee33_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product', 'warehouse', 'branch', 'price_type'), name='unique_active_product_price', nulls_distinct=False),
        ),
    ]
