# Generated by Django 5.1.4 on 2026-06-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_directory_created_at_directory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
