# Generated by Django 5.1.4 on 2026-07-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_currency_exchangerate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
    ]
