# Generated by Django 5.1.4 on 2026-07-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_exchangerate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontotype',
            name='content_type_filter',
            field=models.JSONField(blank=True, default=dict, verbose_name="Доп. фильтр записей (например {'type': 'client'})"),
        ),
    ]
