# Generated by Django 5.1.4 on 2026-07-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_subcontotype_content_type_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.branch', verbose_name='Филиал'),
        ),
    ]
