# Generated by Django 5.1.4 on 2026-07-03 09:29

import accounting.models.counterparty
import accounting.models.employee
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_journalentry_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounting.models.counterparty.counterparty_photo_path, validators=[utils.validators.validate_image_size], verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounting.models.employee.employee_photo_path, validators=[utils.validators.validate_image_size], verbose_name='Фото'),
        ),
    ]
