# Generated by Django 5.1.4 on 2026-07-03 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_employee_counterparty_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('max_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('free_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Бесплатное количество')),
                ('price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_promotions', to='accounting.pricetype', verbose_name='Тип цены (null = для всех)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_promotions', to='accounting.product')),
            ],
            options={
                'verbose_name': 'Акция по количеству',
                'verbose_name_plural': 'Акции по количеству',
                'ordering': ['min_qty'],
            },
        ),
    ]
