# Generated by Django 5.1.4 on 2026-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_quantity_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentparticipant',
            name='role',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
