# Generated by Django 5.1.4 on 2026-07-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_branch_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price_type', models.ForeignKey(blank=True, help_text='Эта цена подставляется по умолчанию в строки приходной накладной', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.pricetype', verbose_name='Тип цены для прихода')),
            ],
            options={
                'verbose_name': 'Настройка документов',
                'verbose_name_plural': 'Настройки документов',
            },
        ),
    ]
