# Generated by Django 5.1.4 on 2026-07-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_documentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.warehouse', verbose_name='Склад'),
        ),
    ]
