# Generated by Django 5.1.4 on 2026-07-04 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_journalentry_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_cogs', to='accounting.account', verbose_name='Счёт себестоимости продаж'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_inventory', to='accounting.account', verbose_name='Счёт учёта товаров'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_receivable', to='accounting.account', verbose_name='Счёт расчётов с покупателем'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_revenue', to='accounting.account', verbose_name='Счёт выручки'),
        ),
    ]
