# Generated by Django 5.1.4 on 2026-07-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_warehouse_cogs_account_warehouse_inventory_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_payable', to='accounting.account', verbose_name='Счёт расчётов с поставщиком'),
        ),
    ]
