# Generated by Django 5.1.4 on 2026-07-05 10:23

import accounting.models.transaction
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_warehouse_payable_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[accounting.models.transaction.validate_nonzero_amount]),
        ),
    ]
