# Generated by Django 5.1.4 on 2026-07-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_transactionline_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='discount_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_discount', to='accounting.account', verbose_name='Счёт скидок'),
        ),
    ]
