# Generated by Django 5.1.4 on 2026-07-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_warehouse_discount_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата снапшота (на конец дня)')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_snapshots', to='accounting.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_snapshots', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'Снапшот остатка склада',
                'verbose_name_plural': 'Снапшоты остатков склада',
                'indexes': [models.Index(fields=['warehouse', 'date'], name='accounting__warehou_fb80ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'product', 'date'), name='unique_warehouse_product_snapshot_date')],
            },
        ),
    ]
