# Generated by Django 5.1.4 on 2026-07-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_warehouseproductsnapshot'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('snapshot_mismatch', 'Расхождение снапшота с проводками'), ('low_stock', 'Остаток ниже минимального')], db_index=True, max_length=30)),
                ('level', models.CharField(choices=[('warning', 'Предупреждение'), ('critical', 'Критично')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Системный алерт',
                'verbose_name_plural': 'Системные алерты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'is_resolved'], name='accounting__type_77a6e7_idx'), models.Index(fields=['content_type', 'object_id'], name='accounting__content_46960c_idx')],
            },
        ),
    ]
