# Generated by Django 5.1.4 on 2026-07-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_systemalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowed_warehouses',
            field=models.ManyToManyField(blank=True, related_name='allowed_products', to='accounting.warehouse', verbose_name='Разрешённые склады (пусто = везде)'),
        ),
    ]
