# Generated by Django 5.1.4 on 2026-07-08 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_product_allowed_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='accounting.employee', verbose_name='Агент'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Район'),
        ),
    ]
