# Generated by Django 5.1.4 on 2026-07-13 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_pricechangehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pricechangehistory',
            name='new_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='pricechangehistory',
            name='old_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='default_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена по умолчанию (0 = бесплатно)'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productrevaluation',
            name='new_cost_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Себестоимость после'),
        ),
        migrations.AlterField(
            model_name='productrevaluation',
            name='old_cost_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Себестоимость до'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='cost_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
