# Generated by Django 5.1.4 on 2026-07-18 06:58

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_alter_documentitem_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='delivery_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент водителю за доставку (%)'),
        ),
        migrations.AddField(
            model_name='document',
            name='delivery_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент водителю за доставку (снимок с контрагента)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='currency',
            field=models.CharField(choices=[('TMT', 'Манаты (TMT)'), ('USD', 'Доллары (USD)')], default='TMT', max_length=3, verbose_name='Валюта склада'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='delivery_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_delivery_expense', to='accounting.account', verbose_name='Счёт расхода на доставку (ЗП водителя)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='driver_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_driver_payable', to='accounting.account', verbose_name='Счёт начислено водителю'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата рейса')),
                ('status', models.CharField(choices=[('new', 'Формируется'), ('delivered', 'Доставлен')], db_index=True, default='new', max_length=10)),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('salary_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ЗП водителя (валюта склада)')),
                ('salary_total_tmt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ЗП водителя (манаты)')),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс USD→TMT на момент доставки')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='accounting.employee', verbose_name='Водитель')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip', to='accounting.journalentry')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='accounting.warehouse', verbose_name='Склад отправления')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounting.trip', verbose_name='Рейс'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'date'], name='accounting__status_986a73_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'date'], name='accounting__driver__9f7805_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['warehouse', 'date'], name='accounting__warehou_f4c204_idx'),
        ),
    ]
