# Generated by Django 5.1.4 on 2026-08-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_counterparty_delivery_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='type',
            field=models.CharField(choices=[('client', 'Клиент'), ('supplier', 'Поставщик'), ('both', 'Клиент и поставщик')], default='client', max_length=20),
        ),
    ]
