# nginx/nginx.conf


# dlya websocket
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

# Логика определения поддоменов (для django-tenants)
server {
    listen 80;
    listen 443 ssl;
    # server_name ~^(?<tenant>.+)\.(?<domain>.+)$;
    # server_name 192.168.25.74.nip.io *.192.168.25.74.nip.io;
    server_name 192.168.43.13.nip.io *.192.168.43.13.nip.io;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Редирект с HTTP на HTTPS
    if ($scheme = "http") {
        return 301 https://$host$request_uri;
    }

    # 1. Статика фронтенда (React)
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Статические файлы Django (админка, rest-framework графический интерфейс)
    location /static/ {
        alias /app/backend_static/;
    }

    # 3. Пользовательские загрузки (Media файлы)
    location /media/ {
        alias /app/backend_media/;
    }

    # 4. Прокси на бэкенд Django (Daphne HTTP)
    location ~ ^/(api|admin)/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }

    # 5. Веб-сокеты Django Channels (на будущее)
    location /ws/ {
        proxy_pass http://backend:8000;
        # proxy_pass http://backend:8000/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection "Upgrade";
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}