# Generated by Django 5.1.4 on 2026-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_platformcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allowed_computer_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Разрешённое имя компьютера (COMPUTERNAME)'),
        ),
        migrations.AddField(
            model_name='company',
            name='pc_lock_enabled',
            field=models.BooleanField(default=False, verbose_name='Работать только на указанном ПК'),
        ),
    ]
