# Generated by Django 5.1.4 on 2026-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_allowed_computer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allowed_hardware_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Разрешённый ID железа (MachineGuid|UUID платы)'),
        ),
    ]
