# Generated by Django 5.1.4 on 2026-08-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_allowed_hardware_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_branch_creation',
            field=models.BooleanField(default=True, verbose_name='Разрешено добавлять филиалы'),
        ),
    ]
