# Generated by Django 5.1.4 on 2026-08-01 05:58

from django.db import migrations, models


def _lock_all_existing_companies(apps, schema_editor):
    # ✅ AlterField сам по себе не трогает уже существующие строки (только
    # новый default для будущих INSERT) — по просьбе владельца платформы
    # явно переводим ВСЕ уже существующие компании на "запрещено", а не
    # только новые. Дальше владелец включает по одной через global-admin.
    Company = apps.get_model('companies', 'Company')
    Company.objects.update(allow_branch_creation=False)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_allow_branch_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='allow_branch_creation',
            field=models.BooleanField(default=False, verbose_name='Разрешено добавлять филиалы'),
        ),
        migrations.RunPython(_lock_all_existing_companies, migrations.RunPython.noop),
    ]
