// core/utils/directoryIcons.ts

import {
  Warehouse,
  Building2,
  Users,
  Truck,
  Wallet,
  FileText,
  ShoppingCart,
  Package,
  Settings,
  BarChart3,
  User,
  Briefcase,
  Boxes,
  Banknote,
  Calculator,
  Shield,
  Wrench,
  Database,
  ClipboardList,
  FolderTree,
} from "lucide-react";

export const DIRECTORY_ICONS = [
  { name: "Warehouse", icon: Warehouse },
  { name: "Building2", icon: Building2 },
  { name: "Users", icon: Users },
  { name: "Truck", icon: Truck },
  { name: "Wallet", icon: Wallet },
  { name: "FileText", icon: FileText },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Package", icon: Package },
  { name: "Settings", icon: Settings },
  { name: "BarChart3", icon: BarChart3 },
  { name: "User", icon: User },
  { name: "Briefcase", icon: Briefcase },
  { name: "Boxes", icon: Boxes },
  { name: "Banknote", icon: Banknote },
  { name: "Calculator", icon: Calculator },
  { name: "Shield", icon: Shield },
  { name: "Wrench", icon: Wrench },
  { name: "Database", icon: Database },
  { name: "ClipboardList", icon: ClipboardList },
  { name: "FolderTree", icon: FolderTree },
];