# Generated by Django 5.1.4 on 2026-06-01 08:15

import users.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path, validators=[utils.validators.validate_image_size]),
        ),
    ]
